[theme]
# Color principal para botones y acentos (Ejemplo: Un azul petrolero)
primaryColor = "#1f77b4"

# Color del fondo principal de la página
backgroundColor = "#0D3552"

# Color del panel lateral y cajas de fondo secundarias
secondaryBackgroundColor = "#f0f2f6"

# Color de las letras
textColor = "#D7DEFA"

# Tipografía (Opciones permitidas: "sans serif", "serif", "monospace")
font = "monospace"
